### ISSUE TITLE
Run simple example

### ISSUE THREAD

**Issue by djmv** [ilyapt/facebook-nologin-scraper#13]
I'm not expert with nodejs but I want run your simple example. I followed the next steps. 
Info about my versions
```
npm --version
6.12.0
node --version
v12.13.0
```

Then, create a .js file with: 
```
var request = require('request');
var scraper = require('facebook-nologin-scraper').default;

request('https://www.facebook.com/zuck',
  {
    headers: {
      'user-agent': 'curl/7.47.0',
      'accept-language': 'en-US,en',
      'accept': '*/*'
    }
  }, function (error, response, body) {
    if (error) {
      throw (error);
    }
    if (response.statusCode === 200) {
      var result = scraper(body);
      console.log(JSON.stringify(result, null, 2));
    } else {
      console.log('HTTP Error: ' + response.statusCode);
    }
});
```
Then install the libraries 
```
npm install request
npm install facebook-nologin-scraper
```
Finally, I got problems with installation of fb-scraper lib
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /node_modules/facebook-nologin-scraper/facebook-nologin-scraper.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/node_modules/facebook-nologin-scraper/facebook-nologin-scraper.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     05_56_356Z-debug.log
```

I don't what do, in other hand I clone this project and try to run but still have problems 
after ```npm install``` and ``` node bin/facebook-nologin-scraper.js https://www.facebook.com/zuck ``` got this

```
internal/modules/cjs/loader.js:302
      throw err;
      ^

Error: Cannot find module '/facebook-nologin-scraper/lib/facebook-nologin-scraper.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:294:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:525:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:781:27)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/facebook-nologin-scraper/bin/facebook-nologin-scraper.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/facebook-nologin-scraper/package.json',
  requestPath: '..'
}
```

**Comment by Ciao121** [comment]
Same here. Non way to install via npm. Non way to make it works installing manually. :(
